<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\StarXelem\StarXelem.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Reference Include="Google.Protobuf">
            <HintPath>..\..\libs\Google.Protobuf.dll</HintPath>
        </Reference>
        <Reference Include="Grpc.Core.Api">
            <HintPath>..\..\libs\Grpc.Core.Api.dll</HintPath>
        </Reference>
        <Reference Include="Grpc.Net.Client">
            <HintPath>..\..\libs\Grpc.Net.Client.dll</HintPath>
        </Reference>
        <Reference Include="StarBreaker.Grpc">
            <HintPath>..\..\libs\StarBreaker.Grpc.dll</HintPath>
        </Reference>
        <Reference Include="StarBreaker.Common">
            <HintPath>..\..\libs\StarBreaker.Common.dll</HintPath>
        </Reference>
        <Reference Include="StarBreaker.DataCore">
            <HintPath>..\..\libs\StarBreaker.DataCore.dll</HintPath>
        </Reference>
        <Reference Include="StarBreaker.DataCore.Generated">
            <HintPath>..\..\libs\StarBreaker.DataCore.Generated.dll</HintPath>
        </Reference>
        <Reference Include="StarBreaker.Extraction">
            <HintPath>..\..\libs\StarBreaker.Extraction.dll</HintPath>
        </Reference>
        <Reference Include="StarBreaker.P4k">
            <HintPath>..\..\libs\StarBreaker.P4k.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\..\libs\Google.Protobuf.dll" CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\libs\Grpc.Core.Api.dll" CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\libs\Grpc.Net.Client.dll" CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\libs\StarBreaker.Common.dll" CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\libs\StarBreaker.DataCore.dll" CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\libs\StarBreaker.DataCore.Generated.dll" CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\libs\StarBreaker.Extraction.dll" CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\libs\StarBreaker.Grpc.dll" CopyToOutputDirectory="PreserveNewest" />
        <Content Include="..\..\libs\StarBreaker.P4k.dll" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>
</Project>
