<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <ApplicationIcon>Assets\xelem-logo.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AsyncImageLoader.Avalonia" Version="3.7.0" />
        <PackageReference Include="Avalonia" Version="11.3.13" />
        <PackageReference Include="Avalonia.Desktop" Version="11.3.13" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.13" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.13" />
        <PackageReference Include="ClosedXML" Version="0.105.0" />
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.13">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageReference Include="FluentAvaloniaUI" Version="2.4.1" />
        <PackageReference Include="FluentIcons.Avalonia.Fluent" Version="2.0.321" />
        <PackageReference Include="Humanizer.Core.fr" Version="3.0.10" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.9" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.9" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.9" />
        <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.5" />
        <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.5" />
        <PackageReference Include="OneOf" Version="3.0.271" />
        <PackageReference Include="System.IO.Hashing" Version="10.0.5" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Views\ContainerTabView.axaml.cs">
        <DependentUpon>ContainerTabView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\FriendListTabView.axaml.cs">
        <DependentUpon>FriendListTabView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\BlueprintListTabView.axaml.cs">
        <DependentUpon>BlueprintTabView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Google.Protobuf">
        <HintPath>..\..\libs\Google.Protobuf.dll</HintPath>
      </Reference>
      <Reference Include="Grpc.Core.Api">
        <HintPath>..\..\libs\Grpc.Core.Api.dll</HintPath>
      </Reference>
      <Reference Include="Grpc.Net.Client">
        <HintPath>..\..\libs\Grpc.Net.Client.dll</HintPath>
      </Reference>
      <Reference Include="StarBreaker.Common">
        <HintPath>..\..\libs\StarBreaker.Common.dll</HintPath>
      </Reference>
      <Reference Include="StarBreaker.DataCore">
        <HintPath>..\..\libs\StarBreaker.DataCore.dll</HintPath>
      </Reference>
      <Reference Include="StarBreaker.DataCore.Generated">
        <HintPath>..\..\libs\StarBreaker.DataCore.Generated.dll</HintPath>
      </Reference>
      <Reference Include="StarBreaker.Extraction">
        <HintPath>..\..\libs\StarBreaker.Extraction.dll</HintPath>
      </Reference>
      <Reference Include="StarBreaker.Grpc">
        <HintPath>..\..\libs\StarBreaker.Grpc.dll</HintPath>
      </Reference>
      <Reference Include="StarBreaker.P4k">
        <HintPath>..\..\libs\StarBreaker.P4k.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="DeployAssets\" />
      <Folder Include="maquettes\" />
    </ItemGroup>
</Project>
