using System.Globalization;
using System.Net;
using System.Text;

namespace StarXelem.VisualJudge;

public static class HtmlReportGenerator
{
    public static string Generate(ComparisonResult result, string outputPath)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
        File.WriteAllText(outputPath, BuildHtml(result));
        return outputPath;
    }

    static string BuildHtml(ComparisonResult result)
    {
        var sb = new StringBuilder();
        string statusClass = result.IsSkipped ? "skip" : (result.IsCompliant ? "pass" : "fail");
        string statusText = result.IsSkipped ? "SKIPPED" : (result.IsCompliant ? "PASS" : "FAIL");

        sb.Append("<!DOCTYPE html><html lang=\"en\"><head>");
        sb.Append("<meta charset=\"UTF-8\">");
        sb.Append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
        sb.Append("<title>Visual Comparison Report</title>");
        sb.Append("<style>");
        sb.Append(Css);
        sb.Append("</style></head><body>");
        sb.Append("<div class=\"container\">");

        // Header
        sb.Append("<h1 style=\"font-size:24px;margin-bottom:8px;\">Visual Comparison Report</h1>");
        sb.AppendFormat(CultureInfo.InvariantCulture, "<p style=\"color:#888;margin-bottom:32px;\">Generated {0} UTC</p>", DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm:ss"));

        // Dashboard
        sb.Append("<div class=\"dashboard\">");
        sb.AppendFormat("<div class=\"stat-card\"><div class=\"stat-value\"><span class=\"{0}\">{1}</span></div><div class=\"stat-label\">Status</div></div>", statusClass, statusText);
        sb.AppendFormat(CultureInfo.InvariantCulture, "<div class=\"stat-card\"><div class=\"stat-value\">{0:F2}</div><div class=\"stat-label\">Semantic Score</div></div>", result.Score);
        sb.AppendFormat(CultureInfo.InvariantCulture, "<div class=\"stat-card\"><div class=\"stat-value\">{0:F1}%</div><div class=\"stat-label\">Pixel Similarity</div></div>", result.Score * 100.0);
        sb.AppendFormat("<div class=\"stat-card\"><div class=\"stat-value\">{0}</div><div class=\"stat-label\">Gaps Found</div></div>", result.Gaps.Length);
        sb.Append("</div>");

        // Skipped banner
        if (result.IsSkipped)
            sb.AppendFormat("<div class=\"skipped-banner\">{0}</div>", WebUtility.HtmlEncode(result.Summary));

        // Gaps table
        if (result.Gaps.Length > 0)
        {
            sb.Append("<section><h2>Detected Gaps</h2>");
            sb.Append("<table><thead><tr><th>#</th><th>Category</th><th>Description</th><th>Severity</th></tr></thead><tbody>");
            for (int i = 0; i < result.Gaps.Length; i++)
            {
                var gap = result.Gaps[i];
                string sevClass = gap.Severity.Equals("critical", StringComparison.OrdinalIgnoreCase) ? "severity-critical" : "severity-minor";
                sb.AppendFormat("<tr><td>{0}</td><td>{1}</td><td>{2}</td><td class=\"{3}\">{4}</td></tr>",
                    i + 1, WebUtility.HtmlEncode(gap.Category), WebUtility.HtmlEncode(gap.Description), sevClass, gap.Severity);
            }
            sb.Append("</tbody></table></section>");
        }

        // Semantic analysis summary
        if (!string.IsNullOrEmpty(result.Summary) && !result.IsSkipped)
            sb.AppendFormat("<section><h2>Semantic Analysis</h2><div class=\"analysis-box\">{0}</div></section>", WebUtility.HtmlEncode(result.Summary));

        // Footer
        sb.Append("<div class=\"footer\">Generated by StarXelem Visual Judge &mdash; Agentic Visual Testing Framework v3</div>");
        sb.Append("</div></body></html>");

        return sb.ToString();
    }

    const string Css = """
        :root { --bg:#0f1117; --surface:#161822; --border:rgba(255,255,255,0.08); --text:#e0e0e0; --muted:#888; }
        * { margin:0; padding:0; box-sizing:border-box; }
        body { font-family:'Segoe UI',system-ui,sans-serif; background:var(--bg); color:var(--text); line-height:1.6; }
        .container { max-width:1400px; margin:0 auto; padding:32px 24px; }
        .dashboard { display:grid; grid-template-columns:repeat(4,1fr); gap:16px; margin-bottom:32px; }
        .stat-card { background:var(--surface); border:1px solid var(--border); border-radius:10px; padding:20px; text-align:center; }
        .stat-value { font-size:36px; font-weight:700; margin-bottom:4px; }
        .stat-label { font-size:12px; color:var(--muted); text-transform:uppercase; letter-spacing:0.5px; }
        .pass { color:#5dcaa5; } .fail { color:#f09595; } .skip { color:#ef9f27; }
        h2 { font-size:18px; margin-bottom:16px; border-bottom:1px solid var(--border); padding-bottom:8px; }
        section { margin-bottom:40px; }
        table { width:100%; border-collapse:collapse; background:var(--surface); border-radius:10px; overflow:hidden; }
        th,td { padding:12px 16px; text-align:left; border-bottom:1px solid var(--border); font-size:13px; }
        th { background:rgba(255,255,255,0.03); color:var(--muted); font-weight:500; text-transform:uppercase; font-size:11px; letter-spacing:0.5px; }
        .severity-critical { color:#f09595; font-weight:600; } .severity-minor { color:#ef9f27; }
        .analysis-box { background:var(--surface); border:1px solid var(--border); border-radius:10px; padding:20px; font-size:14px; line-height:1.8; white-space:pre-wrap; }
        .skipped-banner { background:rgba(239,159,39,0.1); border:1px solid rgba(239,159,39,0.3); border-radius:10px; padding:24px; text-align:center; font-size:16px; color:#ef9f27; }
        .footer { margin-top:48px; padding-top:16px; border-top:1px solid var(--border); font-size:11px; color:var(--muted); text-align:center; }
        """;
}
