<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Headless.XUnit" Version="11.3.14" />
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit.assert" Version="2.9.3" />
    <PackageReference Include="xunit.core" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StarXelem\StarXelem.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Google.Protobuf">
      <HintPath>..\..\libs\Google.Protobuf.dll</HintPath>
    </Reference>
    <Reference Include="Grpc.Core.Api">
      <HintPath>..\..\libs\Grpc.Core.Api.dll</HintPath>
    </Reference>
    <Reference Include="StarBreaker.Common">
      <HintPath>..\..\libs\StarBreaker.Common.dll</HintPath>
    </Reference>
    <Reference Include="StarBreaker.Grpc">
      <HintPath>..\..\libs\StarBreaker.Grpc.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>